<!DOCTYPE html>
<html dir="rtl" lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>اعادة انتاج الخطأ</title>
</head>

<body>
    <div class="book-page">
        <h1 class="book-title">اعادة انتاج الخطأ</h1>
        <div class="content">
            <p>
                ثاني طريقة سوف نتحدث عنها هي التفكير في اعادة انتاج الخطأ, لانه لو ظهر الخطأ مرة
                ثم لم يظهر المرة القادمة هنا اصبحت مشكلة
            </p>
            <p>
                لاحظ هذا الكود: 
            </p>
            <pre><code>
from random import randint

dice_faces = [1, 2, 3, 4, 5, 6]
dice_num = randint(1, 6)
print(dice_faces[dice_num])
            </code></pre>
            <p>
                فلو تحاول تشغيل البرنامج سوف يعمل في بعض الاحيان والبعض الاخر سوف يعطينا 
                error
            </p>
            <p>
                هذا النوع من الاخطاء صعب جدا لانك قد تجرب الكود الخاص بك مرة او 
                مرتين وسوف يعمل ولكن في بعض الاحيان سوف يظهر المشكل ولحل مثل هذه 
                المشاكل علينا اعادة انتاج الخطأ ومحاولة معرفة متى يحدث حتى يظهر الخطأ 
                في كل مرة
            </p>
            <p>
                لدينا قائمة باوجه حجر نرد من 
                1
                الى 
                6
                ولدينا رقم النرد الذي هو رقم عشوائي بين 
                1
                و 
                6
                ونحاول استعمال ذلك الرقم لنحصل على وجه عشوائي لحجر النرد ولكن في 
                بعض الاحيان نحصل على خطأ, فلو نقرأ قليلا حول الدالة 
                randint 
                نجد انها تعمل بشكل مختلف عن دالة ال 
                range 
                وكل من الاعداد 
                1
                و
                6
                سوف يضهر
                فان كان العدد 
                1
                هل سوف يظهر الخطأ؟ بعد التجريب يتضح انه لا يظهر
                ونفس الشيء مع الاعداد 
                2, 3, 4, 5
                ولكن القصة مختلفة مع العدد 
                6
                بحيث في كل مرة نشغل البرنامج مع الرقم 
                6
                المشكل يظهر
            </p>
                        <pre><code>
from random import randint

dice_faces = [1, 2, 3, 4, 5, 6]
dice_num = 6
print(dice_faces[dice_num])
            </code></pre>
            <p>
                اذن لا يمكننا استعمال العدد 
                6
                لان القوائم تبدأ من ال 
                0
                اذن اخر عنصر موجود عند المؤشر 
                5
            </p>
                        <pre><code>
from random import randint

dice_faces = [1, 2, 3, 4, 5, 6]
dice_num = randint(0, 5)
print(dice_faces[dice_num])
            </code></pre>
            <p>
                والان بعد ما اصلحنا الكود فان الخطأ لن يظهر من جديد.
            </p>
        </div>
    </div>
</body>

</html>